#ifndef TREXQUANTTAKEHOME_BOOKKEEPING_ORDER_BOOK_H
#define TREXQUANTTAKEHOME_BOOKKEEPING_ORDER_BOOK_H

class OrderBook {
    public:

    private:
};

#endif // TREXQUANTTAKEHOME_BOOKKEEPING_ORDER_BOOK_H